version: "3.1"
services:
  postgres:
    container_name: postgres_telegram_bot
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "6312:5432"
#    volumes:
#      - ./db/postgresql/data:/var/lib/postgresql/data
#  redis:
#    image: redis:latest
#    container_name: redis
#    restart: always
#    command: redis-server --appendonly yes
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./db/redis/data:/root/redis
#      - ./db/redis/redis.conf:/usr/local/etc/redis/redis.conf
#    environment:
#      - REDIS_PORT=6379
#      - REDIS_DATABASES=16
#      - REDIS_APPENDONLY=yes
#      - REDIS_APPEND_FILENAME=appendonly.aof
#      - REDIS_APPENDFSYNC=everysec