// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"
)

type Querier interface {
	Delete(ctx context.Context, id int64) error
	Get(ctx context.Context, id int64) (*User, error)
	Upsert(ctx context.Context, arg *UpsertParams) error
}

var _ Querier = (*Queries)(nil)
