version: "3.1"
services:
  db:
    container_name: pg_tg_bot
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "4321:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
