// Code generated by ifacemaker; DO NOT EDIT.

package user

import (
	"context"

	"github.com/3Danger/telegram_bot/internal/models"
)

// Репозиторий пользователей
type Repo interface {
	ApproveChanges(ctx context.Context, id int) error
	DeleteDraft(ctx context.Context, id int) error
	GetCompleted(ctx context.Context, id int) (*models.User, error)
	GetDraft(ctx context.Context, id int) (*models.User, error)
	SetAdditional(ctx context.Context, id int, additionalParams string) error
	SetFirstName(ctx context.Context, id int, firstNameParams string) error
	SetLastName(ctx context.Context, id int, lastNameParams string) error
	SetPhone(ctx context.Context, id int, phoneParams string) error
	SetUserType(ctx context.Context, id int, userTypeParams string) error
	UpsertDraft(ctx context.Context, user models.User) error
}
