// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"time"
)

// Все пользователи
type User struct {
	ID int64
	// Заполнены все полня и регистрация завершена
	HasRegistered bool
	// Является ли поставщиком
	IsSupplier bool
	// Имя
	FirstName string
	// Фамилия
	LastName string
	// Отчество
	Surname string
	// Телефон
	Telephone string
	// Номер whatsapp
	Whatsapp string
	// Ник в телеграмме
	Telegram  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
