// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type RecordingMode string

const (
	RecordingModeDraft     RecordingMode = "draft"
	RecordingModeCompleted RecordingMode = "completed"
)

func (e *RecordingMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordingMode(s)
	case string:
		*e = RecordingMode(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordingMode: %T", src)
	}
	return nil
}

type NullRecordingMode struct {
	RecordingMode RecordingMode `json:"recording_mode"`
	Valid         bool          `json:"valid"` // Valid is true if RecordingMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordingMode) Scan(value interface{}) error {
	if value == nil {
		ns.RecordingMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordingMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordingMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordingMode), nil
}

type UserType string

const (
	UserTypeUnknown  UserType = "unknown"
	UserTypeSupplier UserType = "supplier"
	UserTypeCustomer UserType = "customer"
)

func (e *UserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserType(s)
	case string:
		*e = UserType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserType: %T", src)
	}
	return nil
}

type NullUserType struct {
	UserType UserType `json:"user_type"`
	Valid    bool     `json:"valid"` // Valid is true if UserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserType) Scan(value interface{}) error {
	if value == nil {
		ns.UserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserType), nil
}

// Все пользователи
type User struct {
	// ID пользователя
	ID int64 `json:"id"`
	// Статус регистрации
	RecordingMode RecordingMode `json:"recording_mode"`
	// Тип пользователя
	UserType UserType `json:"user_type"`
	// Имя
	FirstName string `json:"first_name"`
	// Фамилия
	LastName string `json:"last_name"`
	// Телефон
	Phone string `json:"phone"`
	// Доп. контакты, инфо
	Additional string `json:"additional"`
	IsDeleted  bool   `json:"is_deleted"`
	// Дата создания записи
	CreatedAt time.Time `json:"created_at"`
	// Дата обновления записи
	UpdatedAt time.Time `json:"updated_at"`
}
