// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"time"
)

// Все пользователи
type User struct {
	ID int64
	// Является ли поставщиком
	IsSupplier bool
	// Имя
	FirstName string
	// Фамилия
	LastName string
	// Отчество
	Surname string
	// Телефон
	Phone string
	// Номер whatsapp
	Whatsapp string
	// Ник в телеграмме
	Telegram  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
