// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

import (
	"context"
)

type Querier interface {
	ApproveChanges(ctx context.Context, id int64) error
	Delete(ctx context.Context, arg *DeleteParams) error
	Get(ctx context.Context, arg *GetParams) (*User, error)
	GetDraft(ctx context.Context, id int64) (*User, error)
	SetAdditional(ctx context.Context, arg *SetAdditionalParams) error
	SetFirstName(ctx context.Context, arg *SetFirstNameParams) error
	SetLastName(ctx context.Context, arg *SetLastNameParams) error
	SetPhone(ctx context.Context, arg *SetPhoneParams) error
	SetUserType(ctx context.Context, arg *SetUserTypeParams) error
	Upsert(ctx context.Context, arg *UpsertParams) error
}

var _ Querier = (*Queries)(nil)
